//

export const ogrDrivers = [
  { key: 'JP2OpenJPEG', value: 'JP2OpenJPEG', text: 'JPEG-2000' },
  { key: 'PDF', value: 'PDF', text: 'Geospatial PDF' },
  { key: 'MBTiles', value: 'MBTiles', text: 'MBTiles' },
  { key: 'ESRI Shapefile', value: 'ESRI Shapefile', text: 'ESRI Shapefile' },
  { key: 'MapInfo File', value: 'MapInfo File', text: 'MapInfo File' },
  { key: 'CSV', value: 'CSV', text: 'Comma Separated Value (.csv)' },
  { key: 'GML', value: 'GML', text: 'Geography Markup Language (GML)' },
  { key: 'GPX', value: 'GPX', text: 'GPX' },
  { key: 'LIBKML', value: 'LIBKML', text: 'Keyhole Markup Language (LIBKML)' },
  { key: 'KML', value: 'KML', text: 'Keyhole Markup Language (KML)' },
  { key: 'GeoJSON', value: 'GeoJSON', text: 'GeoJSON' },
  { key: 'GeoJSONSeq', value: 'GeoJSONSeq', text: 'GeoJSON Sequence' },
  { key: 'GPKG', value: 'GPKG', text: 'GeoPackage' },
  { key: 'SQLite', value: 'SQLite', text: 'SQLite / Spatialite' },
  { key: 'ODBC', value: 'ODBC', text: 'ODBC' },
  { key: 'MSSQLSpatial', value: 'MSSQLSpatial', text: 'Microsoft SQL Server Spatial Database' },
  { key: 'PostgreSQL', value: 'PostgreSQL', text: 'PostgreSQL/PostGIS' },
  { key: 'MySQL', value: 'MySQL', text: 'MySQL' },
  { key: 'DXF', value: 'DXF', text: 'AutoCAD DXF' },
  { key: 'GeoRSS', value: 'GeoRSS', text: 'GeoRSS' },
  { key: 'PGDUMP', value: 'PGDUMP', text: 'PostgreSQL SQL dump' },
  { key: 'CouchDB', value: 'CouchDB', text: 'CouchDB / GeoCouch' },
  { key: 'Cloudant', value: 'Cloudant', text: 'Cloudant / CouchDB' },
  { key: 'ODS', value: 'ODS', text: 'Open Document/ LibreOffice / OpenOffice Spreadsheet' },
  { key: 'XLSX', value: 'XLSX', text: 'MS Office Open XML spreadsheet' },
  { key: 'ElasticSearch', value: 'ElasticSearch', text: 'Elastic Search' },
  { key: 'MVT', value: 'MVT', text: 'Mapbox Vector Tiles' },
];
