export const ogrDrivers = [
  { key: 'CSV', value: 'CSV', text: 'Comma Separated Value (.csv)' },
  { key: 'DXF', value: 'DXF', text: 'AutoCAD DXF' },
  { key: 'ESRI Shapefile', value: 'ESRI Shapefile', text: 'ESRI Shapefile' },
  { key: 'GeoJSON', value: 'GeoJSON', text: 'GeoJSON' },
  { key: 'GeoJSONSeq', value: 'GeoJSONSeq', text: 'GeoJSON Sequence' },
  { key: 'GPKG', value: 'GPKG', text: 'GeoPackage' },
  { key: 'GML', value: 'GML', text: 'Geography Markup Language (GML)' },
  { key: 'GPX', value: 'GPX', text: 'GPX' },
  { key: 'KML', value: 'KML', text: 'Keyhole Markup Language (KML)' },
  { key: 'LIBKML', value: 'LIBKML', text: 'Keyhole Markup Language (LIBKML)' },
  { key: 'MapInfo File', value: 'MapInfo File', text: 'MapInfo File' },
  { key: 'MBTiles', value: 'MBTiles', text: 'MBTiles' },
  { key: 'MVT', value: 'MVT', text: 'Mapbox Vector Tiles' },
  { key: 'ODS', value: 'ODS', text: 'Open Document/ LibreOffice / OpenOffice Spreadsheet' },
  { key: 'PDF', value: 'PDF', text: 'Geospatial PDF' },
  { key: 'PGDUMP', value: 'PGDUMP', text: 'PostgreSQL SQL dump' },
  { key: 'SQLite', value: 'SQLite', text: 'SQLite / Spatialite' },
  { key: 'XLSX', value: 'XLSX', text: 'MS Office Open XML spreadsheet' },
];
