exports.ogrDrivers = {
  JP2OpenJPEG: { app: 'JPEG', ext: '.jpg' },
  PDF: { app: 'GeoPDF', ext: '.pdf' },
  MBTiles: { app: 'MBTiles', ext: '.mbtiles' },
  'ESRI Shapefile': { app: 'SHP', ext: '.shp' },
  'MapInfo File': { app: 'MapInfo', ext: 'todo' },
  CSV: { app: 'CSV', ext: '.csv' },
  GML: { app: 'GML', ext: '.gml' },
  GPX: { app: 'GPX', ext: '.gpx' },
  LIBKML: { app: 'LIBKML', ext: '.kml' },
  KML: { app: 'KML', ext: '.kml' },
  GeoJSON: { app: 'GeoJSON', ext: '.geojson' },
  GeoJSONSeq: { app: 'NdGeoJSON', ext: '.ndgeojson' },
  GPKG: { app: 'GPKG', ext: '.gpkg' },
  SQLite: { app: 'SQLite', ext: '.sqlite' },
  ODBC: { app: 'ODBC', ext: '.todo' },
  MSSQLSpatial: { app: 'SQLServer', ext: '.todo' },
  PostgreSQL: { app: 'PostgreSQL', ext: '.todo' },
  MySQL: { app: 'MySQL', ext: '.todo' },
  DXF: { app: 'DXF', ext: '.dxf' },
  GeoRSS: { app: 'GeoRSS', ext: '.todo' },
  PGDUMP: { app: 'PGDUMP', ext: '.todo' },
  CouchDB: { app: 'CouchDB', ext: '.todo' },
  Cloudant: { app: 'Cloudant', ext: '.todo' },
  ODS: { app: 'ODS', ext: '.todo' },
  XLSX: { app: 'XLSX', ext: '.xlsx' },
  ElasticSearch: { app: 'ES', ext: '.todo' },
  MVT: { app: 'MVT', ext: '.mvt' },
};
