exports.ogrDrivers = {
  CSV: { app: 'CSV', ext: '.csv' },
  DXF: { app: 'DXF', ext: '.dxf' },
  'ESRI Shapefile': { app: 'SHP', ext: '.shp' },
  GeoJSON: { app: 'GeoJSON', ext: '.geojson' },
  GeoJSONSeq: { app: 'NdGeoJSON', ext: '.ndgeojson' },
  GPKG: { app: 'GPKG', ext: '.gpkg' },
  GML: { app: 'GML', ext: '.gml' },
  GPX: { app: 'GPX', ext: '.gpx' },
  KML: { app: 'KML', ext: '.kml' },
  LIBKML: { app: 'LIBKML', ext: '.kml' },
  'MapInfo File': { app: 'MapInfo', ext: 'tab' },
  MBTiles: { app: 'MBTiles', ext: '.mbtiles' },
  MVT: { app: 'MVT', ext: '' },
  ODS: { app: 'ODS', ext: '.ods' },
  PDF: { app: 'GeoPDF', ext: '.pdf' },
  PGDUMP: { app: 'PGDUMP', ext: '.pgdump' },
  SQLite: { app: 'SQLite', ext: '.sqlite' },
  XLSX: { app: 'XLSX', ext: '.xlsx' },
};
